# Generated by Django 5.0.3 on 2024-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0002_alter_leaf_birth_date_alter_leaf_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
