# Generated by Django 5.0.6 on 2024-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0003_alter_leaf_birth_date_alter_leaf_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaf',
            name='quotation',
        ),
        migrations.AddField(
            model_name='leaf',
            name='type_of_loss',
            field=models.CharField(choices=[('during_pregnancy', 'During Pregnancy'), ('at_birth_or_shortly_after', 'At Birth or Shortly After')], default='during_pregnancy', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaf',
            name='memory',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='parent1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
